### PR TITLE
Add wallet keys list to wallet settings

### PR DESCRIPTION
**Pull request by ben-kaufman**
Solve #332

### CODE REVIEW

**Comment by mflaxman** [comment]
Looks good!

Is there any way to see the number of signatures need (`m` in `m-of-n`)? I'm not seeing it here but could be missing something.

Nitpick: any reason that my coldcard seed is `xpub...` and my others are `Zpub...`? That will like confuse newbies.

**Comment by ben-kaufman** [comment]
Well the number of signatures is always visible at the left sidebar under the wallet name, but I could add it also somewhere there if you think that'll be better.

Not sure about the xpub zpub, for me it shows zpub for all, including coldcard, so seems strange but I'll take another look

**Comment by stepansnigirev** [comment]
xpub representation depends on how you imported them:
- import via USB automatically converts xpubs to slip-132 (zpubs, Zpubs etc)
- import via SD card or pasting in the text field keeps them in the same form they were imported. Probably coldcard uses xpubs in multisig wallet file, so we keep them as xpubs.

Maybe we should always convert them to slip-132 so a simple copy-paste to Electrum and other software wallets would work.

**Comment by stepansnigirev** [comment]
Actually all hardware wallets display xpubs, so better to display xpubs in this table

**Comment by mflaxman** [comment]
> all hardware wallets display xpubs, so better to display xpubs in this table

Not true @stepansnigirev!: 
46C53153-580F-4D67-BC55-B6CD5EBCEDEF_1_105_c

I currently don't have a strong opinion on which to use/how (xpub vs Zpub), but it does seem inherently confusing to end-users to have to deal with both :(

**Comment by ben-kaufman** [comment]
Oh, we didn't check Cobo :( I'll add there a Toggle SLIP-132 button (or maybe any simpler name suggestion?) which will just toggle between xpub and Zpub in the table, is that good?

**Comment by mflaxman** [comment]
Toggle seems like a good solution! Maybe in the future there will be more of a standard, but giving users access to all the info for now seems like the best choice to me.

**Comment by ben-kaufman** [comment]
Cool, added it in #343

**Pull request merged**
