### PR TITLE
feat:(startup) style startup and preferences

### PR DESCRIPTION
**Pull request by otkstdio**
This fixes https://github.com/cryptoadvance/specter-desktop/issues/2151 and also styles the startup screen

### CODE REVIEW

**Comment by moneymanolis** [comment]
There are two "Choose file buttons" under Advanced in the Preferences since the styling of the input (type file) was changed (it had opacity 0 before):

grafik

Just add class="hidden"?

More problematic, saving doesn't work for me, also not on master.

**Comment by moneymanolis** [comment]
There also still merge conflicts.

**Review by moneymanolis — CHANGES_REQUESTED** [review]
See comment

**Comment by otkstdio** [comment]
@moneymanolis I'm confused, that screenshot looks nothing like it did on when i was running it, are you sure you had the most up to date version?

**Comment by otkstdio** [comment]
@moneymanolis Issues resolved 👍

**Review by moneymanolis — APPROVED** [review]

**Pull request merged**
