### PR TITLE
Adding QR message signing and address verification for Jade

### PR DESCRIPTION
**Pull request by PaarthAgarwal**
Addresses https://github.com/cryptoadvance/specter-desktop/issues/2089.
Hoping it's the right direction to go about.
@moneymanolis have a look.

### CODE REVIEW

**Comment by moneymanolis** [comment]
Yup, looks good.

**Comment by PaarthAgarwal** [comment]
> Yup, looks good. Might even be enough already.

yayyyy

**Comment by moneymanolis** [comment]
@bitcoinhelp this PR would also set the taproot support for Jade to true, is this correct?

**Comment by moneymanolis** [comment]
Successfully tested the message signing feature with firmware 0.1.43 alpha1:

grafik

I also tested the verify via QR functionality (this PR also sets `qr_code_support_verify = True`), also worked. I've changed the PR title to account for this.

**Comment by bitcoinhelp** [comment]
> @bitcoinhelp this PR would also set the taproot support for Jade to true, is this correct?

No taproot support for Jade yet actually

**Comment by moneymanolis** [comment]
> > @bitcoinhelp this PR would also set the taproot support for Jade to true, is this correct?
> 
> No taproot support for Jade yet actually

OK, I figured. I remove that line

**Review by k9ert — APPROVED** [review]

**Pull request merged**
