### PR TITLE
Hot wallet advanced configurations

### LINKED ISSUE #490: Encryption password not working on Bitcoin Core (hot wallet) device
Is the encryption password field on the **New Device > Device Type > Bitcoin Core** screen refer to a BIP38-encrypt Passphrase?

If so, leaving the field blank or adding a password returns exactly the same zpub. This makes it impossible to import BIP32 protected wallets.

Am I missing something?

See test below:

```
labor better pink common fashion unit strategy swift depend resemble street win lab opera ozone fee cancel doctor design bleak dish odor bachelor escape
↓
[57c6d2be/84h/0h/0h]zpub6qgcH99CzfwsYujyHnGQKA7ZoUWWAxWBX6CcMGQJDutyAyA3EkJjhdptynYTAEU5h92jpbp6X2x9XNRxcCPh8C24dt4RfFzSmFEDd4ZPDAb
```

```
labor better pink common fashion unit strategy swift depend resemble street win lab opera ozone fee cancel doctor design bleak dish odor bachelor escape
+
gLkEZy44[zA;xA{Z
↓
[57c6d2be/84h/0h/0h]zpub6qgcH99CzfwsYujyHnGQKA7ZoUWWAxWBX6CcMGQJDutyAyA3EkJjhdptynYTAEU5h92jpbp6X2x9XNRxcCPh8C24dt4RfFzSmFEDd4ZPDAb
```

Frame 16

### LINKED ISSUE #498: hot wallets don't support custom derivation paths
Unlike when adding a hardware device, viewing a hot wallet does not provide the "add more keys" option for custom derivation paths. Is this a Bitcoin Core limitation or just something that hasn't been added to the UI yet?

### PR DESCRIPTION
**Pull request by ben-kaufman**
This PR adds some more advanced configurations for using Bitcoin Core hot wallet, including:

- BIP39 passphrase support (close #490)
- Custom derivation paths support (close #498)
- Custom range for import of addresses (Bitcoin Core 0.21 should make it obsolete, eventually...)
- Allow adding more keys to an existing hot wallet.
- Improves terminology to distinguish between wallet file encryption password and BIP39 passphrase.

### CODE REVIEW

**Comment by ben-kaufman** [comment]
Compiled `specterd` for testing:
[specterd-0.8.2-pre1-osx.zip](https://github.com/cryptoadvance/specter-desktop/files/5387261/specterd-0.8.2-pre1-osx.zip)

**Comment by jlopp** [comment]
Slight issue when trying to add a key with path "m/49/1/0"

`Traceback (most recent call last):
  File "/home/jameson/code/specter-desktop-benk/env/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jameson/code/specter-desktop-benk/env/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jameson/code/specter-desktop-benk/env/lib/python3.7/site-packages/flask_login/utils.py", line 269, in decorated_view
    return func(*args, **kwargs)
  File "/home/jameson/code/specter-desktop-benk/src/cryptoadvance/specter/controller.py", line 1740, in device
    keys_range=[range_start, range_end],
  File "/home/jameson/code/specter-desktop-benk/src/cryptoadvance/specter/devices/bitcoin_core.py", line 76, in add_hot_wallet_keys
    xpubs = derive_xpubs_from_xprv(xprv, paths, wallet_manager.rpc)
  File "/home/jameson/code/specter-desktop-benk/src/cryptoadvance/specter/devices/bitcoin_core.py", line 221, in derive_xpubs_from_xprv
    parent = get_child(parent, idx)
  File "/home/jameson/code/specter-desktop-benk/src/cryptoadvance/specter/devices/bitcoin_core.py", line 253, in get_child
    raise ValueError("Can't do non-hardened")
ValueError: Can't do non-hardened`

**Comment by ben-kaufman** [comment]
@jlopp now it should work with non-hardened derivations as well.

**Comment by jlopp** [comment]
tested; ACK

**Pull request merged**
