### PR TITLE
make electrum watch-only export

### PR DESCRIPTION
**Pull request by mflaxman**
https://github.com/cryptoadvance/specter-desktop/issues/212#issuecomment-699587232

Note that this only works for multisig (single sig would require adding a crypto library).

### CODE REVIEW

**Review by ben-kaufman — APPROVED** [review]
Tested, works :)

**Comment by stepansnigirev** [comment]
Awesome, thanks!
Why do we need a crypto library for single sig?

**Comment by mflaxman** [comment]
I was confused at the relationship between devices/keys and was wrong. Single-sig now works and the code is a bit easier to read.

Give this a shot and see if you like it, I think it's a nice addition (and I want to feature it for out of band receive address verification).

**Comment by stepansnigirev** [comment]
Yes, I think it's a great feature. Let me some time to test it tonight and we can merge :)

**Pull request merged**
