### PR TITLE
Bugfix: Updating the auto-withdrawal in Swan integration could lead to an error

### PR DESCRIPTION
**Pull request by moneymanolis**
If you had 10 addresses reserved already and updated the withdrawal it tried to reserve 10 more addresses and went into the else part of `if len(addresses) < num_addresses `in `reserve_addresses` in `service.py` - since 10 is equal to 10.
It then returned a list of addr objs from `wallet.get_associated_addresses() `instead of a list of addr strs.

With this PR we return an empty list if there are already enough addresses reserved and don't even make another call to the Swan API if this is the case.

This PR also adds more tests to test the` reserve_addresses()` method from the Service class.
@k9ert about to whether we keep your tests with the mocks which I renamed to `test_reserve_addresses_with_mocks`

Fixes https://github.com/cryptoadvance/specter-desktop/issues/1963

### CODE REVIEW

**Comment by moneymanolis** [comment]
TODO

- [ ] Fix the tests

**Comment by moneymanolis** [comment]
Perhaps handy to fix this little UI bug here in this PR as well, the front end is not showing the chosen threshold but always weekly:

grafik

**Comment by k9ert** [comment]
Can you rename `tests/test_services.py` to something like `tests/test_ext_swan_services.py`?
I'm missing the link between the test file and what's actually tested. Maybe there is more stuff in there which is rather indeed testing the services-core functionality but at least your test is testing ext-swan code?!

**Comment by k9ert** [comment]
> TODO
> 
>     * [ ]  Fix the tests

I guess you rather need to fix the implementation here, as `Swan is expecting an alomost flat list of addresses`, no?

**Comment by moneymanolis** [comment]
> The code is testing service-functionality but the tests are imho (?!) not testing the changes in the SwanService-class. Might be difficult to test as you need to mock super().

Let me see what I can add, the main change is in the reserve_addresses() method of the service class which is used by the reserve_addresses() method of the Swan "service" class.

**Comment by moneymanolis** [comment]
> UI bug: the front end is not showing the chosen threshold but always weekly:
> 
> grafik
> 
> Addressed in [9ac7bad](https://github.com/cryptoadvance/specter-desktop/commit/9ac7bad4dbe1991022ed94f0e1889cd35b93e284)

Now:

https://user-images.githubusercontent.com/70536101/203388538-a638ea6a-af9e-42b8-99d2-807065923ec1.mov

**Review by k9ert — APPROVED** [review]

**Pull request merged**
