### PR TITLE
UI/Design proposal: Redesign the main page

### LINKED ISSUE #1619: UI/Design proposal: The main page could be improved
The main/landing page could be improved. Here's my suggestion:

| Before (1920x1080 / iPad / iPhone) | After (1920x1080 / iPad / iPhone) |
| --------- | ------ |
|  |  |
|  |  |
|  |  |

### PR DESCRIPTION
**Pull request by cypherhoodlum**
closes #1619.
Redesign the main page.

### CODE REVIEW

**Comment by moneymanolis** [comment]
Wow, thanks for this great PR, looks great. Happy to test / review it. Flexboxes for the win!

**Comment by moneymanolis** [comment]
I like it, but could we perhaps make the ghost a little bit smaller? Sth. like this: 
@moritzwietersheim would that work for you then?

image

What I used for this (not sure whether it is better to use px or percentages ...):

```
.main-specter-background-image{
    position: absolute;
    bottom: 20px;
    left: 175px;
    opacity: 0.3;
    z-index: 0;
}
```

**Comment by moritzwietersheim** [comment]
Alright :) ...let's go with the smaller ghost in the watermark. 
But let's see how the feedback from the users is, and take it from there.

**Comment by moneymanolis** [comment]
@cypherhoodlum what do you think?

**Review by moneymanolis — CHANGES_REQUESTED** [review]
Smaller ghost

**Comment by k9ert** [comment]
> I can push the changes directly to this remote branch of yours if you want, @cypherhoodlum. Just let me know what you think.

If you create a PR, you can choose whether it's possible. So if it's possible, please do it!

**Comment by cypherhoodlum** [comment]
I think the smaller ghost works great. Percentages might be better than pixels in the positioning. @k9ert if you can push directly to this remote branch, go ahead. Is some approval still needed on my part to get this PR merged? Not sure if I need to approve some changes or not.

**Comment by k9ert** [comment]
> @k9ert if you can push directly to this remote branch, go ahead.

I'm not so much into UIUX. @moneymanolis considered to make the change. Would be better if you'd do it, though. The failing test is unfortunately some flaky thingy and unrelated.
Happy to merge it after that change.

**Review by moneymanolis — APPROVED** [review]
Smaller ghost was integrated here: https://github.com/cryptoadvance/specter-desktop/pull/1620/commits/25e1e649305acde85cb337db80775589ef91332a

@cypherhoodlum if you want you could perhaps check whether the smaller ghost looks good like this on different devices / viewports, which I haven't tested - but if you don't have time for it, I am fine with merging like this.

**Comment by cypherhoodlum** [comment]
Can confirm that the smaller ghost looks good on various screen sizes. It starts to wander outside the gray border a bit on bigger screens but it's nothing to worry about, it still looks pretty good. I think this is ready to be merged. Thanks for the improvements!

**Comment by cypherhoodlum** [comment]
Actually there was still an issue with the 'Using Specter from a remote machine?' box combined with the ghost image. I converted the ghost image into a css background-image of the main div and now the image is always contained inside the div as well. I also placed the 'Using Specter from a remote machine?' box into a more fitting place.



Scrolldown:



Let me know if there are any further issues and I'll try to fix them.

**Comment by cypherhoodlum** [comment]
And just to be clear I forced the 'Using Specter from a remote machine?' into view only momentarily. The render if-clause hasn't been changed in the actual commits.

**Comment by moneymanolis** [comment]
I think the css background-image change was another improvement to make it more robust, excellent work, @cypherhoodlum. Merging this now.

**Pull request merged**
