### PR TITLE
add pip-compile and hash support for security/reproducibility

### PR DESCRIPTION
**Pull request by mflaxman**
I'm running into a strange bug in https://github.com/cryptoadvance/specter-desktop/issues/476, and I suspect that broken versioning is at play (though I'm not certain) so I decided to add this to specter, especially since it is very good for security. Read more about `--require-hashes` [here](https://lil.law.harvard.edu/blog/2019/05/20/improving-pip-compile-generate-hashes/).

I updated the steps for pip to first install from `requirements.txt` and then second `install -e .` as this [seems to be the best practice for validating those hashes on build](https://stackoverflow.com/questions/46835953/hash-checking-in-setup-py-install-requires) (kind of hackey).

### CODE REVIEW

**Comment by mflaxman** [comment]
Foiled by my own `black`ifier being down! This does indeed pass locally:
```
$ black . --check
All done! ✨ 🍰 ✨
64 files would be left unchanged.
```

**Comment by mflaxman** [comment]
Black is now fixed in https://github.com/cryptoadvance/specter-desktop/pull/497

Once that is merged this should pass.

**Comment by mflaxman** [comment]
Black passes again, this is ready to merge! (Don't know how to get TravisCI to run)

**Comment by k9ert** [comment]
Thank you very much! This is really awesome PR. I didn't knew that this is possible and also haven't understood all implications but this is definitely very usefull. I tested the branch and the pip-installation worked. So this LGTM, i'd merge.
@ben-kaufman  and @stepansnigirev please confirm, at least one of you!

**Comment by stepansnigirev** [comment]
Looks good to me!

**Review by stepansnigirev — APPROVED** [review]

**Pull request merged**
