### PR TITLE
HWI upgrade to 2.4.x

### PR DESCRIPTION
**Pull request by k9ert**
@moneymanolis for testing trezor 3

### CODE REVIEW

**Comment by k9ert** [comment]
successfully tested with Ledger, Trezor One, Coldcard and Bitbox02.

**Comment by moneymanolis** [comment]
hwi support for Trezor 3 only from version 2.4.0 on!
See: https://github.com/bitcoin-core/HWI/releases/tag/2.4.0

**Review by esmaili76000 — APPROVED** [review]

**Review by esmaili76000 — COMMENTED** [review]
[]()5d1ce2c9907e9cf658aa71dc0605212a0c61c764

**Comment by moneymanolis** [comment]
Tested with the new Trezor 3 - worked all fine! (signed a transaction on testnet). You need to set up the Trezor 3 with Trezor Suite beforehand obviously.

**Review by moneymanolis — APPROVED** [review]
Tested with Trezor 3.

**Pull request merged**
