### PR TITLE
Adding Foundation Passport as supported device

### PR DESCRIPTION
**Pull request by jonathancross**
Per https://github.com/Foundation-Devices/passport-firmware/issues/6#issuecomment-946897266

### CODE REVIEW

**Comment by k9ert** [comment]
Thanks for the addition.
Did you tested the passport support? QR code and SD-card? Which version did you used exactly?

**Comment by jonathancross** [comment]
Unfortunately I do not have a Passport device to test.
I was researching support for various wallets (like Specter) as a prerequisite towards ordering one.

**Comment by k9ert** [comment]
Sorry but i don't think we should merge this if we can't even find someone who confirms that it works. We have to pray that there isn't someone who complains that it's not working.

**Comment by jonathancross** [comment]
No problem, makes sense.
Hopefully I can get a device and test in the future.

**Pull request closed without merging**
