### PR TITLE
Prepare the v0.3.0 release

### PR DESCRIPTION
**Pull request by k9ert**
* Added release-notes
* added ledger minimum firmware version to readme.md

Anything else which we should include before the release?

### CODE REVIEW

**Comment by stepansnigirev** [comment]
I would like to add https://github.com/cryptoadvance/specter-desktop/pull/118 to this release - then we can make a simultaneous release of specter-desktop and specter-diy.

**Comment by k9ert** [comment]
Let's do that!

**Comment by k9ert** [comment]
In order to test the animated QR-codes, Stepan created a pre-release binary of specter-diy:
https://github.com/cryptoadvance/specter-desktop/files/4574177/specter-diy.bin.zip
I'll soon also create a test-release of specter-desktop.

**Comment by k9ert** [comment]
Seems like the github-notification is still broken but the build is green!
https://travis-ci.com/github/k9ert/specter-desktop/builds/165241246

**Pull request merged**
