### PR TITLE
Cleanup:(ui) Remove Specter Ghost from the background of the about page

### PR DESCRIPTION
**Pull request by otkstdio**
Simple PR to remove the css from the about page that sets the Specter ghost as the background image.

### CODE REVIEW

**Comment by k9ert** [comment]
Why do you think that is something we should do?

**Comment by otkstdio** [comment]
Hey @k9ert this was a request from @moritzwietersheim 👍

**Comment by k9ert** [comment]
Ah, yeah, got it. That was already a controversial feature when we merged it and @moritzwietersheim doesn't like it but he's a bit alone on that front. I'd suggest to focus for now on the uncontroversial changes and kick this one down the road for some time.
Maybe you can create a screenshot of before/after and embed it here. Maybe one in each comment and we just put that up for vote by giving thumbs up on the corresponding comment?!

**Comment by otkstdio** [comment]
@k9ert Sounds good. I'll attach before and after images below.

**Comment by otkstdio** [comment]
Before

Screen Shot 2022-11-15 at 10 57 27 AM

**Comment by otkstdio** [comment]
After

Screen Shot 2022-11-15 at 10 57 14 AM

**Comment by moneymanolis** [comment]
Please don't forget that this was a [FOSS contribution](https://github.com/cryptoadvance/specter-desktop/pull/1620) by @cypherhoodlum and nobody complained about it so far, I like it. Let's focus on more important stuff on the front end like buggy functionality. There are more than enough issues here.

**Comment by moneymanolis** [comment]
Closing this as discussed, @cypherhoodlum, your ghost stays ;-)

**Pull request closed without merging**
