### PR TITLE
support scanning animated QR codes

### PR DESCRIPTION
**Pull request by stepansnigirev**
related to https://github.com/cryptoadvance/specter-diy/pull/55

### CODE REVIEW

**Comment by gorazdko** [comment]
doesnt work for me. I get a warning: the camera stream is only accessible if the page is transferred via https.

Prepending `https://` then gives: ssl received a record that exceeded the maximum permissive length

**Comment by stepansnigirev** [comment]
Are you running specter on localhost?
Camera is available either if you use localhost, or over https

**Comment by gorazdko** [comment]
Yes im running localhost. Camera works perfectly fine for non-animated QRs but not for animated ones.

**Comment by stepansnigirev** [comment]
Hm... Interesting... I'll double-check with firefox.

**Comment by gorazdko** [comment]
i think i made mistake, didnt check out the branch correctly

**Comment by stepansnigirev** [comment]
I added a QR progress that shows which parts are already scanned and which not.
Displays "👻" for every scanned QR code and "❔" for every part that is not scanned yet.

In reality I don't even notice this progress bar because all parts are scanned very fast.

**Comment by stepansnigirev** [comment]
>  your master branch didnt return anything in the console, now a null is returned if the transaction cannot be parsed. A descriptive warning would be nicer.

Will do, thanks!

**Comment by stepansnigirev** [comment]
@gorazdko not sure if it is what you meant,
but now web browser alerts when it failed to combine transactions.

**Comment by gorazdko** [comment]
I tested also scanning a single random qr and the popup is there which is correct. Works great!

**Comment by k9ert** [comment]
Great! I've tested the animated gif feature (animating on the PC). Was not able to test the other direction but my webcam-situation is ... horrible. Bad hand with webcams.
I guess we can merge that and then start final testing? 
Maybe we should release finally on halving day :-) ?

**Comment by stepansnigirev** [comment]
> Maybe we should release finally on halving day
good idea!

**Pull request merged**
