### PR TITLE
Add transaction details on signing page

### PR DESCRIPTION
**Pull request by ben-kaufman**
Solves #124 

Adds the ability to see more transaction information (fees, size, outputs with their details, raw PSBT etc.).
I'm definitely not a designer so any ideas on how to make it look prettier are highly welcomed, though I think it will be also fine as is. Here are a few screenshots of how that looks:

Screenshot3
Screenshot1
Screenshot2

### CODE REVIEW

**Comment by stepansnigirev** [comment]
Copy didn't work for me.
According to [w3schools](https://www.w3schools.com/howto/howto_js_copy_clipboard.asp) the script needs to select the text that will be copied before copying.

Also instead of using javascript to toggle transaction details I would recommend making it a checkbox and defining visibility in css.
Here is an example including changing the label without any js:
https://jsfiddle.net/uw5pt63b/1/

**Comment by stepansnigirev** [comment]
Also, for inputs it would be nice to see address labels and addresses.
For outputs I would include addresses as well, not just labels.

**Comment by ben-kaufman** [comment]
Updated with all the above, should be good now.

**Comment by stepansnigirev** [comment]
Looks great!

**Pull request merged**
