### PR TITLE
Update wallet.py

### PR DESCRIPTION
**Pull request by pathtoknowhere**
- Include fee whenever transaction is a spend

### CODE REVIEW

**Comment by k9ert** [comment]
Hi, thanks for your PR. This additional call to core would probably affect many more transactions as just these 1-2 unconfirmed ones. This could impact the performance if you have many transactions in your wallet.

Can you elaborate why you want that and what you mean by "for applications accessing Specter's API"?

**Comment by pathtoknowhere** [comment]
Thanks for the consideration and opportunity to explain the proposed changes.

Specter Desktop (SD) is a great tool for wallet management\monitoring and its API leaves the door wide-open for other applications (such as [WARden](https://github.com/pxsocs/warden)) to make good use of the data it aggregates. I was recently referred to WARden (W) by a user in the SD Telegram chat, and it's an interesting\useful project that I believe is very complementary to SD. It focuses on portfolio performance metrics (NAV, etc.) and relies on data returned by SD. The problem is that the data is incomplete; in order to accurately calculate these metrics and reconstruct wallet balances from transaction histories, fees data is required. A knock-on effect is that W cannot correctly assess wallets that contain CoinJoin re-mix transactions (from Samourai, for example). This is because, for a re-mix, the fee comprises the total value of the transaction. Finally, even as I review my histories in SD, I often find myself wanting to know the fee for a particular spend.

**Comment by k9ert** [comment]
Yes, agree, warden is awesome and we need a proper API at some point. Some time ago, we worked on https://github.com/cryptoadvance/specter-desktop/pull/713 in order to get to a reasonable API-approach. However, @pxsocs at some point did not had the need anymore.
So instead of this PR, i'd rather be interested in revive #713 , what do you think?

**Comment by pathtoknowhere** [comment]
I just read over [#713](https://github.com/cryptoadvance/specter-desktop/pull/713) and I think it'd be really beneficial to have a dedicated API. It even looks like you guys completed nearly all of the work already; but, didn't @ben-kaufman [ultimately decide that the changes weren't necessary](https://github.com/cryptoadvance/specter-desktop/pull/713#issuecomment-775520633)?

**Comment by ben-kaufman** [comment]
Not really, I think having a better structured and formal API like in #713 would be best, but need someone to pick it up again and migrate the changes we have done so far.

**Comment by pathtoknowhere** [comment]
Okay, great - @pxsocs, what do you think?

**Comment by pxsocs** [comment]
Just catching up to this. I agree that a proper API like in #713 would be best. Unfortunately I'm really short on time to pick that up right now but happy to help testing.

**Comment by pathtoknowhere** [comment]
> Not really, I think having a better structured and formal API like in #713 would be best, but need someone to pick it up again and migrate the changes we have done so far.

My apologies, @ben-kaufman - I misread the comment from @pxsocs. He decided to close the PR at the time because he felt the existing code was sufficient, not you.

I'm not able to commit to managing #713 going forward either, but I'll also try to help however I can. After re-reading the thread again, I'm still not even clear how to proceed. Perhaps you or @k9ert can comment?

**Pull request closed without merging**
