### PR TITLE
Move to HWI v2

### PR DESCRIPTION
**Pull request by ben-kaufman**
Updates HWI to v2.0.0

Stuff this PR still needs (blocking for now):
- [x] Update from RC to the final version of HWI 2.0.0 when it's out
- [x] Update Specter DIY HWI code to the new API
- [x] Trezor needs change verification for multisig

### CODE REVIEW

**Comment by hzoman** [comment]
Any idea on when this (and the BB02 multisig support) will roll out now that HWI 2.0 was released March 15th?

**Comment by ben-kaufman** [comment]
I think we'll have this released within a week

**Comment by stepansnigirev** [comment]
https://github.com/cryptoadvance/specter-diy/blob/master/hwidevice.py

This should make DIY working with HWI v2 API

**Comment by ben-kaufman** [comment]
Should be ready to test now and merge if all works. No Trezor multisig change verification for now, hope it'll be added soon to HWI (I'll try myself if I get some time).

**Comment by k9ert** [comment]
Tested Trezot SingeSig for receive-address verification and sending. Works. I think we should merge and test further with the new release.

**Comment by k9ert** [comment]
Tested again (including 8d0c3c2)  with my Trezor one, this time with a change-address. Not sure what to expect but i couldn't detect any change.

**Comment by stepansnigirev** [comment]
> Tested again (including [8d0c3c2](https://github.com/cryptoadvance/specter-desktop/commit/8d0c3c292ec695700ff71acc1c17f36eb1c95528)) with my Trezor one, this time with a change-address. Not sure what to expect but i couldn't detect any change.

Just checked with the latest firmware of Trezor T and Trezor One - works for me. Can you check with https://github.com/cryptoadvance/specter-desktop/pull/1001/commits/b97a3dbc69c0d33a958ef945acf8ebcd728c8f95 and make sure the firmware is the latest?

**Comment by ben-kaufman** [comment]
Tested with a KeepKey 1410ebc794c92522f63fdd68e299be73202f90d4 works well

**Comment by k9ert** [comment]
I'd say, let's merge this and test on the release-binary.

**Pull request merged**
