### PR TITLE
Restore ability to import address labels of unlabeled addresses

### PR DESCRIPTION
**Pull request by relativisticelectron**
As described in https://github.com/cryptoadvance/specter-desktop/pull/1470#pullrequestreview-823070898  the PR https://github.com/cryptoadvance/specter-desktop/pull/1470 broke the ability to import electrum address labels (for which most of the cases no prior address label was defined).

This PR implements recommended changes of https://github.com/cryptoadvance/specter-desktop/pull/1470#pullrequestreview-823070898 .   
@moneymanolis :  If these changes are not desired for the use-case of Specter CSV  and Specter JSOn import, please comment.

### CODE REVIEW

**Comment by moneymanolis** [comment]
First, thanks very much for your PR @relativisticelectron! I only made a slight modification of the import of a Specter CSV file to not import all the labels from such a CSV, that would probably confuse users (that was also the reason to use only labeled addresses in the first place). I think the logic is better handled now and less error prone. I also made minor changes to comments. @k9ert if relativisticelectron is OK with my modification, my review would be done.

**Review by moneymanolis — CHANGES_REQUESTED** [review]
See my comment above.

**Comment by relativisticelectron** [comment]
> First, thanks very much for your PR @relativisticelectron! I only made a slight modification of the import of a Specter CSV file to not import all the labels from such a CSV, that would probably confuse users (that was also the reason to use only labeled addresses in the first place). I think the logic is better handled now and less error prone. I also made minor changes to comments. @k9ert if relativisticelectron is OK with my modification, my review would be done.

@moneymanolis : Thanks for the changes.  To summarize; the behavior is now:

- Specter JSON and Electrum JSON will import all labels
- Labels from Specter CSV which start with "Address #" will be disregarded.  The remainder will be imported


 
Am I correct in assuming, that the Specter JSON does not contain labels starting with "Address #"?
If this is so, then this PR can be merged.

**Comment by moneymanolis** [comment]
> Am I correct in assuming, that the Specter JSON does not contain labels starting with "Address #"? If this is so, then this PR can be merged.

Yes, the Specter JSON actually has a special key "labels" which has as its value a dictionary with all the labels set by the user that are not the standard "Address #" and its corresponding addresses.

**Review by moneymanolis — APPROVED** [review]

**Pull request merged**
