### PR TITLE
BugFix: Update black version to fix error

### PR DESCRIPTION
**Pull request by relativisticelectron**
I had the issue as described in https://github.com/psf/black/issues/2964  and upgrading the black version as recommended: https://github.com/psf/black/issues/2964#issuecomment-1080974737 fixed it.

### CODE REVIEW

**Comment by moneymanolis** [comment]
@k9ert makes sense to upgrade this, too, no? So far, we only upgraded black for CI (#1642) as far as I can see.

**Comment by k9ert** [comment]
Yes, definitely! There is also `test_requirements.txt` but it seems that one is already updated for some reason.

**Review by k9ert — APPROVED** [review]

**Comment by relativisticelectron** [comment]
Can it be merged?

**Comment by moneymanolis** [comment]
Yes, just merged, thanks for your continuos work and support @relativisticelectron 💪

**Pull request merged**
