### PR TITLE
Show and set subtract from field on send max

### LINKED ISSUE #1663: Send max with multiple recepients
When I send money to several addresses and click "Send max" not on the first one, Specter subtracts fee from the first output.

Expected behaviour: fee should be subtracted from the output where I clicked "Send max".
Previously we had an input that was specifying which output to subtract from, not sure why it was removed.

image

image

### PR DESCRIPTION
**Pull request by ahv15**
fixes #1663

### CODE REVIEW

**Comment by relativisticelectron** [comment]
Tested and it solves https://github.com/cryptoadvance/specter-desktop/issues/1663

**Comment by moneymanolis** [comment]
@ahv15 thanks for the PR and @relativisticelectron thanks for testing. I'll will check it, too.

**Comment by moneymanolis** [comment]
@relativisticelectron I've reviewed it. I will add two slight optimisations but I also wanted to add a Cypress test to have better test coverage here (and of course sth. is not quite working well with the tests). Should be merged today or tomorrow, though.

**Comment by relativisticelectron** [comment]
Great, thanks.

**Comment by moneymanolis** [comment]
Additions in https://github.com/cryptoadvance/specter-desktop/pull/1744/commits/04f94931132ff3f017f509f055cbef4e3667a16e:

- EventListener of subtract from recipient input field changed to also capture entering a number directly
- Changed name of subtract from recipient input for the form to avoid mixups
- Cypress test added for sending a transaction with multiple recipients

**Review by moneymanolis — APPROVED** [review]
I've already directly pushed my two small optimisations.

**Review by k9ert — APPROVED** [review]

**Pull request merged**
