### PR TITLE
Fix issue with Daemonize

### PR DESCRIPTION
**Pull request by ben-kaufman**
I've been experiencing an issue with the `--daemon` option of Specter not working, and not even outputting any crash logs or something of the sort. I've searched a bit aand looks like this line in the Daemonize lib is where it fails: https://github.com/thesharp/daemonize/blob/39a880f74c1d8ea09fa44fe2b99dec1c961201a9/daemonize.py#L136

When disabling this the daemon starts working for me.

### CODE REVIEW

**Comment by k9ert** [comment]
Fine by me. But let's wait until the other two are merged.

**Comment by stepansnigirev** [comment]
@k9ert why to wait? They are kinda independent.

On the mobile pull request I will continue working with styles not touching anything on the python side.

**Comment by k9ert** [comment]
> @k9ert why to wait? They are kinda independent.

Yes, you're right. It was just some horror on git fuckups ruining a day of work. But in these simple cases it's just a click of a button to do the rebase.
Let's merge when the build is green!

**Comment by stepansnigirev** [comment]
@ben-kaufman it didn't work for me.

Can you check https://github.com/cryptoadvance/specter-desktop/pull/116 ?
It fixed the issue for me, I wonder if it will work for you as well...

**Comment by ben-kaufman** [comment]
Replaced with #116

**Pull request closed without merging**
