### PR TITLE
Fix BitBox02 timeout issue

### PR DESCRIPTION
**Pull request by ben-kaufman**
Fix issue where the request to the BitBox02 throws error due to the timeout.

### CODE REVIEW

**Comment by ben-kaufman** [comment]
Note that I couldn't reproduce the issue myself, but got one user so far confirming this works.

**Comment by djpnewton** [comment]
does the timeout happen while unlocking the bitbox02? I might have hit this issue too, so I could test this fix

**Comment by ben-kaufman** [comment]
@djpnewton , not exactly, the issue is that it seems to happen to some users even after unlocking the BitBox02. Could not reproduce myself, but if you can it'll be very helpful!

**Comment by k9ert** [comment]
I've created https://github.com/cryptoadvance/specter-desktop/releases/tag/v1.3.1-pre2 in order to test this PR.

**Pull request merged**
