### PR TITLE
Use the configured bitcoind data directory (regression)

### PR DESCRIPTION
**Pull request by shesek**
Without this fix, the configured data directory is ignored and the default is always used instead.

This did not happen with v1.5.0, it appears that the regression was introduced [in 22cd3e93](https://github.com/cryptoadvance/specter-desktop/commit/22cd3e9372abd0f95ce679d02711fb2bde86e126#diff-04de6bab3ea93d6516d4769480f8ab06fa7e2eb339fc1c0dd302292fa820fd94L115) (#1333).

### CODE REVIEW

**Comment by shesek** [comment]
BTW, on an unrelated note, it would be nice if the data directory was configurable using environment variables too and not only using the config file, so that it wouldn't be necessary to [fiddle with the config file](https://github.com/ez-org/eznode/blob/13a30717beac68d2d51130f2152501b35ade282f/specter/run#L22) to configure the data directory programmatically.

**Comment by ben-kaufman** [comment]
Thanks! I think adding the data-dir also as parameter makes sense. Would you like to do that or you'd prefer that I will?

**Comment by shesek** [comment]
> adding the data-dir also as parameter

What do you mean? Isn't that what 695515939367b2bf5d8b3ef645e266779e213e01 does?

**Comment by ben-kaufman** [comment]
Yeah I meant the env variable. I'll check about it then, thanks!

**Pull request merged**
