### PR TITLE
fix bad error-messaging

### PR DESCRIPTION
**Pull request by k9ert**
In the case of using spectrum, errors which came from the electrum server, did not got shown very well to the user.
In one case we had 
image

This is caused by the server not returning json which in turn is caused by the client not adding "Accept:application/json" to the header. Also the errorClass translation from electrum -> spectrum -> specter-ext -> specter -> user was quite improvable.

### CODE REVIEW

**Comment by moneymanolis** [comment]
@k9ert can remove these console.logs in this PR before the release:

https://github.com/cryptoadvance/specter-desktop/blob/714a8ae771526a6d8b0d956d04f3471919756f5c/src/cryptoadvance/specter/templates/includes/hwi/components/wallet.jinja#L51

especially the console log of the PSBT should be removed, what do you think?

**Comment by moneymanolis** [comment]
getting this error right now when using 1 sat / vbyte fee on testnet:
image
```
[2024-05-15 19:11:01,406] ERROR in controller: Uncaught exception: string indices must be integers
[2024-05-15 19:11:01,410] ERROR in controller: Traceback (most recent call last):
  File "/Users/manolis/.pyenv/versions/.specter/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/manolis/.pyenv/versions/.specter/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/manolis/.pyenv/versions/.specter/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/manolis/coding/repos/specter-desktop/src/cryptoadvance/specter/server_endpoints/wallets/wallets_api.py", line 182, in broadcast
    app.specter.broadcast(tx)
  File "/Users/manolis/coding/repos/specter-desktop/src/cryptoadvance/specter/specter.py", line 513, in broadcast
    res = self.rpc.sendrawtransaction(raw)
  File "/Users/manolis/coding/repos/specter-desktop/src/cryptoadvance/specter/rpc.py", line 507, in fn
    r = self.multi([(method, *args)], **kwargs)[0]
  File "/Users/manolis/coding/repos/specter-desktop/src/cryptoadvance/specterext/spectrum/bridge_rpc.py", line 102, in multi
    result = [
  File "/Users/manolis/coding/repos/specter-desktop/src/cryptoadvance/specterext/spectrum/bridge_rpc.py", line 103, in <listcomp>
    self.spectrum.jsonrpc(
  File "/Users/manolis/.pyenv/versions/.specter/lib/python3.10/site-packages/cryptoadvance/spectrum/spectrum.py", line 499, in jsonrpc
    raise e
  File "/Users/manolis/.pyenv/versions/.specter/lib/python3.10/site-packages/cryptoadvance/spectrum/spectrum.py", line 489, in jsonrpc
    res = m(*args, **kwargs)
  File "/Users/manolis/.pyenv/versions/.specter/lib/python3.10/site-packages/cryptoadvance/spectrum/spectrum.py", line 56, in wrapper
    return f(*args, **kwargs)
  File "/Users/manolis/.pyenv/versions/.specter/lib/python3.10/site-packages/cryptoadvance/spectrum/spectrum.py", line 716, in sendrawtransaction
    res = self.sock.call("blockchain.transaction.broadcast", [hexstring])
  File "/Users/manolis/.pyenv/versions/.specter/lib/python3.10/site-packages/cryptoadvance/spectrum/elsock.py", line 564, in call
    raise RPCError(res["error"]["message"], res["error"]["code"])
TypeError: string indices must be integers
```

**Comment by moneymanolis** [comment]
@k9ert do we perhaps have to parse the JSON string into a dictionary correctly? 

We should in any case better check whether `res` is a dict and not just a string with sth. like:
```
if isinstance(res, dict) and "error" in res:
    error = res.get("error", {})
    error_code = error.get("code")
    error_message = error.get("message")
    if error_code is not None and error_message is not None:
        raise RPCError(error_message, error_code)
    else:
        raise SpectrumInternalException(res)
```

**Comment by k9ert** [comment]
> especially the console log of the PSBT should be removed, what do you think?

Happy to remove them but they are not part of this PR so maybe we can do that in some other PR.

**Comment by k9ert** [comment]
Can't reproduce the "TypeError: string indices must be integers" issue. But i implemented your proposal anyway here:
https://github.com/cryptoadvance/spectrum/pull/55
Please approve and i create yet another Spectrum release and use it here.

**Comment by moneymanolis** [comment]
I could broadcast with Spectrum and 1 sat fee on testnet without error now (might be that we are catching it now gracefully, which might be fine since it aligns with bitcoind).

**Review by moneymanolis — APPROVED** [review]

**Pull request merged**
