### PR TITLE
Add Custom Specter Dock Icon

### PR DESCRIPTION
**Pull request by otkstdio**
This PR adds a new Icon for the Specter App.

shot

### CODE REVIEW

**Comment by moneymanolis** [comment]
Tray icon looks like this @moritzwietersheim 

grafik

**Review by moneymanolis — APPROVED** [review]

**Comment by otkstdio** [comment]
Added themed menu icons above ^

dark
light

**Review by moneymanolis — CHANGES_REQUESTED** [review]
Event listener for changes in dark / light mode.

**Review by moneymanolis — APPROVED** [review]

**Comment by k9ert** [comment]
This is how it looks like on Linux:
image

**Pull request merged**
