### PR TITLE
Re-added expand-more.svg

### LINKED ISSUE #1881: 404 on static/img/expand-more.svg
**Describe the bug**
I'm seeing

```
[2022-09-11 12:21:22,961] ERROR in controller: Could not find Resource (404): http://127.0.0.1:25441/static/img/expand-more.svg
[2022-09-11 12:21:22,962] INFO in _internal: 127.0.0.1 - - [11/Sep/2022 12:21:22] "GET /static/img/expand-more.svg HTTP/1.1" 404 -
```

on my console log when running Specter while developing a plugin.

**To Reproduce**
1. Generate a plugin with the plugin generator.
2. Configure it to show up in the menu.
3. Click the plugin in the menu.
4. You should see the 404 above.

**Expected behavior**
Don't expect to see any 404s.

**Desktop (please complete the following information):**
- Running Specter Desktop 1.12.0.

**Additional context**
The request originates with the menu Jinja template:

Screen Shot 2022-09-11 at 12 25 49 PM

### PR DESCRIPTION
**Pull request by PaarthAgarwal**
An attempt to fix #1881.
I have re-added exapnd-more.svg.

### CODE REVIEW

**Comment by moneymanolis** [comment]
@PaarthAgarwal thanks, could you also add the `expand-less.svg`, this seems to be missing as well:

grafik

**Comment by PaarthAgarwal** [comment]
> @PaarthAgarwal thanks, could you also add the `expand-less.svg`, this seems to be missing as well:
> 
> grafik

I can't find these files in previous commits. If you can tell me someplace from where I can copy or download it then I'll add it here

**Comment by k9ert** [comment]
Can you try to find it like this: https://stackoverflow.com/questions/953481/how-do-i-find-and-restore-a-deleted-file-in-a-git-repository ?

**Comment by k9ert** [comment]
I've added the file in #1881

**Comment by PaarthAgarwal** [comment]
> I've added the file in #1881

Thanks @k9ert. The command worked just now too haha

**Review by k9ert — APPROVED** [review]

**Pull request merged**
