### PR TITLE
Remove local caching

### PR DESCRIPTION
**Pull request by ben-kaufman**
The goal of this PR is mainly performance improvements and bug fixes.
The current Addresses history feature is nice, but it relies on data that is very hard and network costly to retrieve from Bitcoin Core. Since it is not really in the scope of Specter's architecture to be an indexing server, and since this feature seems to be too problematic without such a server, we decided to remove it, at least until we add support for existing indexing servers like Electrum Server.

Changes:
- Remove caching of transactions
- Remove Addresses History tab
- Merge the UTXO tab with Transactions tab
- Transaction history pagination

This should resolve: #238 #239

### CODE REVIEW

**Comment by stepansnigirev** [comment]
All transactions look like unconfirmed now...

**Comment by ben-kaufman** [comment]
I don't see it on my side... Do they also say pending? Or are they saying confirmed but still displayed in unconfirmed color?

**Comment by stepansnigirev** [comment]
All pending...
Screenshot 2020-07-17 at 17 36 06

**Comment by ben-kaufman** [comment]
And generating a new block just to make sure doesn't help I guess? Any idea on how to reproduce or nothing special?

**Comment by stepansnigirev** [comment]
Also transaction history page became much slower...

**Comment by ben-kaufman** [comment]
I made a slight change which should make it a bit faster. For me it's now pretty much the same as before, maybe even slightly better (with the last commit), can you please try with that?

**Pull request merged**
