### PR TITLE
Bugfix: netlify

### PR DESCRIPTION
**Pull request by k9ert**
Currently we're suffering:
```
6:36:44 PM: Successfully installed Markdown-3.4.1 PyYAML-6.0 ghp-import-2.1.0 mdx_truly_sane_lists-1.2 mergedeep-1.3.4 mkdocs-1.3.0 mkdocs-video-1.3.0 packaging-21.3 pyparsing-3.0.9 pyyaml-env-tag-0.1 watchdog-2.1.9
6:36:45 PM: ERROR    -  Config value: 'markdown_extensions'. Error: Failed loading extension "mdx_truly_sane_lists".
6:36:45 PM: Aborted with 1 Configuration Errors!
6:36:45 PM: ​
6:36:45 PM: ────────────────────────────────────────────────────────────────
6:36:45 PM:   "build.command" failed                                        
6:36:45 PM: ────────────────────────────────────────────────────────────────
```

The successfull build looked like this:
```
10:05:10 AM: Successfully installed Markdown-3.3.7 PyYAML-6.0 ghp-import-2.1.0 mdx_truly_sane_lists-1.2 mergedeep-1.3.4 mkdocs-1.3.0 mkdocs-video-1.3.0 packaging-21.3 pyparsing-3.0.9 pyyaml-env-tag-0.1 watchdog-2.1.9
```

So let's pin markdown ...

### CODE REVIEW

**Comment by relativisticelectron** [comment]
There is also an open issue: https://github.com/radude/mdx_truly_sane_lists/issues/9

**Comment by relativisticelectron** [comment]
I included the fix  here https://github.com/relativisticelectron/mdx_truly_sane_lists/commit/148d94fcf5c4e4c9d9b0a7cbd976a4f3107b9678 and one can install the package via: 
`pip3 install git+https://github.com/relativisticelectron/mdx_truly_sane_lists`

**Comment by relativisticelectron** [comment]
I think the owner of https://github.com/radude/mdx_truly_sane_lists  is not around any more..... So my PR will not be merged there.

**Comment by k9ert** [comment]
He seems to be active in some private repos recently. Might still have luck. Anyway, i'd merge this as soon as someone approves it.

**Comment by k9ert** [comment]
Ok, i think this PR is then obsolete. Closing.

**Pull request closed without merging**
