### PR TITLE
Translation from English to Portuguese Finished.

### PR DESCRIPTION
**Pull request by KoreaComK**
Translation from English to Portuguese Finished.

### CODE REVIEW

**Comment by ben-kaufman** [comment]
Thanks! Just need this fix and we could merge https://github.com/KoreaComK/specter-desktop/pull/1

**Comment by KoreaComK** [comment]
Hey @ben-kaufman ,
I merged the PR.
Cheers!

**Comment by ben-kaufman** [comment]
Thanks, I just merged the first Portugese PR and I see there are conflicts. Would you need help to resolve it?

**Comment by KoreaComK** [comment]
Hi @ben-kaufman , I think that I need help because i didn't find the conflicts that github are saying that has.

**Comment by KoreaComK** [comment]
I tried to change a line to see if it solve the conflicts, but I doesn't.
image
It seems that I can't see the conflicts too.

**Comment by kdmukai** [comment]
I fixed the conflict in the Portuguese `.po` file and merged the latest two commits in from `master`.

**Comment by KoreaComK** [comment]
Thanks @kdmukai  :)

**Pull request merged**
