### PR TITLE
release notes for v1.3.0

### PR DESCRIPTION
**Pull request by k9ert**
- ToDos:

- [ ] change the date on the release-notes
- [ ] have more testing

### CODE REVIEW

**Comment by kdmukai** [comment]
Should also note the breaking change for anyone with an existing Tor setup. The previous `CookieAuthentication` method will no longer work. They'll have to hash the new `torrc_password` from Specter's `config.json`.

see updated guidance: https://github.com/cryptoadvance/specter-desktop/blob/master/docs/tor.md#configure-tor

**Comment by AaronDewes** [comment]
Since v0.11.0-pre1 you're using Gemran names of the months. Is this intentional? (Dezember, Januar, Februar, März instead of December, January, February, March).

**Comment by ben-kaufman** [comment]
@kdmukai I think an existing Tor setup would still work just not with the "built in" stuff no?

**Comment by kdmukai** [comment]
You wouldn't be able to start the hidden service with `CookieAuthentication`, no? I'm pretty sure I explicitly tested this.

https://github.com/cryptoadvance/specter-desktop/blob/master/src/cryptoadvance/specter/util/tor.py#L13

```
def start_hidden_service(app):
    app.specter.tor_controller.authenticate(
        password=app.specter.config.get("torrc_password", "")
    )
```

**Comment by ben-kaufman** [comment]
Oh right yes. I was thinking just on simple Tor calls and forgetting about the hidden service

**Comment by AaronDewes** [comment]
> Since v0.11.0-pre1 you're using German names of the months. Is this intentional? (Dezember, Januar, Februar, März instead of December, January, February, March).

@k9ert What is the reason for that?

**Comment by k9ert** [comment]
Good question, apologize. Sorry, we were maybe a bit too much focused on the the smoothness of the new download-feature. This will be a topic for a bugfix-release.

**Pull request merged**
