### PR TITLE
Finish Send Screen UX Flows & Table Headers for TX + UTXOs

### PR DESCRIPTION
**Pull request by otkstdio**
WIP

### CODE REVIEW

**Review by k9ert — APPROVED** [review]

**Review by k9ert — CHANGES_REQUESTED** [review]
Just realized that it's WIP. YOu can create Draft reuests. Those will then be better visible to be WIP. I'll switch it to draft ...

**Comment by moneymanolis** [comment]
Fixes https://github.com/cryptoadvance/specter-desktop/issues/2091 and https://github.com/cryptoadvance/specter-desktop/issues/2090

**Comment by moneymanolis** [comment]
Speed up the Transaction screen not done yet:

grafik

**Comment by moneymanolis** [comment]
Wondering about the styling of an address belong to the wallet, is this intended like this @otkstdio 

grafik

**Comment by moneymanolis** [comment]
Remaining tasks here @otkstdio
- [ ] Fix the "is my address" styling in the send dialogue
- [ ] Try to address the super wide table if there are unconfirmed transactions (RBF buttons pop up then)
- [ ] Grid lines of the tx table look strange on Firefox

**Comment by moneymanolis** [comment]
There was one Spectrum feedback screen missing (that it is incompatible to use Spectrum alongside a Core connection). Changed it in accordance with the other Spectrum screens in https://github.com/cryptoadvance/specter-desktop/pull/2099/commits/ca77eb432e211a53cd662cc7cd2ae96b01d1d67b @otkstdio:

grafik

**Review by moneymanolis — APPROVED** [review]

**Review by k9ert — APPROVED** [review]

**Pull request merged**
