### PR TITLE
Release binaries

### PR DESCRIPTION
**Pull request by k9ert**
see #323 

For now, only linux binaries get created and uploaded.

### CODE REVIEW

**Comment by stepansnigirev** [comment]
I cherry-picked `fix the build` commit to fix the build on master. Was broken by #322 
Do you think it's realistic to get build jobs for osx, win and aarch64 in this PR?

**Comment by k9ert** [comment]
Gitlab provides its runner-binary for [windows](https://docs.gitlab.com/runner/install/windows.html) and [MacOS](https://docs.gitlab.com/runner/install/osx.html). They even have publicly available windows runners. I'm not too happy to use them for security-reasons, though. Building and testing is one thing (which we're already not covering with public but a private runner) but releasing is even more security critical.

**Comment by stepansnigirev** [comment]
So if I understand this PR correctly, it will create a unix binary and upload it to your fork, right?

**Comment by k9ert** [comment]
Yes, that was wrong (fixed). Also there is documentation missing which i should put to https://github.com/cryptoadvance/specter-desktop/blob/master/docs/continuous-integration.md
Give me some more time and i'll try to create a windows-binary as well. There i have to fiddle around with picking the right runner. When i have that, maybe someone else can do the same for MacOS binaries (I don't own a Mac but can provide a windows-runner).
By the way i really think we should restrict ourself to private runners. Sooner or later we want to sign the builds (and hash them before that). Even though it might be possible on public runners, it's a very bad idea imho.

**Pull request merged**
