### PR TITLE
Tor integration

### PR DESCRIPTION
**Pull request by kdmukai**
Experimental branch to offer an option to launch Specter Desktop as a Tor hidden service. It will still be available on the local network as usual but will now also be externally available via a secret onion address.

Interested to hear your thoughts and feedback.

### CODE REVIEW

**Comment by kdmukai** [comment]
Tor integration was based on:
https://stem.torproject.org/tutorials/over_the_river.html

**Comment by stepansnigirev** [comment]
That's awesome! I will try it out today.
I wanted to have an onion hidden service for Specter but I had no idea how to do it :)

**Comment by stepansnigirev** [comment]
Merged. Works perfectly! Thanks!

**Comment by stepansnigirev** [comment]
Damn it, I messed up... 
Doesn't work if Tor is not configured.

**Pull request merged**
