### PR TITLE
Update wallet_send.jinja

### PR DESCRIPTION
**Pull request by VCBhatawadekar**
I added a placeholder which is by default 0 and deleted any prefilled active value.

### CODE REVIEW

**Comment by VCBhatawadekar** [comment]
this change is regarding #1413

**Review by moneymanolis — APPROVED** [review]

**Comment by VCBhatawadekar** [comment]
> We had a look and this is a reasonable reuqest to ask but it breaks a functionality: `fillform`. @moneymanolis is working on that. Will be merged when ready.

Oh... I was not aware that `fillform` would require changes too

**Comment by VCBhatawadekar** [comment]
> > We had a look and this is a reasonable reuqest to ask but it breaks a functionality: `fillform`. @moneymanolis is working on that. Will be merged when ready.
> 
> Oh... I was not aware that `fillform` would require changes too

This is my first try to contribute.... can anyone explain what is next step?

**Comment by moneymanolis** [comment]
Thanks for the contribution, it is now merged.

**Pull request merged**
