### PR TITLE
Feature: stacktrack 0.2.1 and spectrum 0.3.1

### PR DESCRIPTION
**Pull request by k9ert**

### CODE REVIEW

**Comment by moneymanolis** [comment]
I am getting this error when trying to access the wallets overview:

```
Traceback (most recent call last):
  File "/Users/heinzi/.pyenv/versions/.new-stacktrace-version/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/heinzi/.pyenv/versions/.new-stacktrace-version/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/heinzi/.pyenv/versions/.new-stacktrace-version/lib/python3.10/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/heinzi/.pyenv/versions/.new-stacktrace-version/lib/python3.10/site-packages/cryptoadvance/specterext/stacktrack/controller.py", line 79, in wallets_overview
    txs: list = _extract_txs(wallets)
  File "/Users/heinzi/.pyenv/versions/.new-stacktrace-version/lib/python3.10/site-packages/cryptoadvance/specterext/stacktrack/controller.py", line 124, in _extract_txs
    return sorted(txs, key=lambda d: d["blockheight"], reverse=True)
TypeError: '<' not supported between instances of 'NoneType' and 'int'
```

Chart in an individual wallet works fine, though (didn't work for me with the prior version):

grafik

**Comment by moneymanolis** [comment]
I've investigated the error a bit and it is very likely due to `blockheight` being `None`. The respective test for this (`def test_txlist`) didn't capture this since it was:
`assert tx.blockheight is None or tx.blockheight > 200`

Tagging @wombat6 as well here.

**Review by moneymanolis — CHANGES_REQUESTED** [review]
Handling of unconfirmed transactions with `blockheight None` has to be fixed.

**Comment by k9ert** [comment]
> I am getting this error when trying to access the wallets overview:

Mitigated: In `v0.2.1` you get a msg like:

> Due to https://github.com/cryptoadvance/specterext-stacktrack/issues/12 the chart is not available for unconfirmed transactions. Check the logs for details

> I've investigated the error a bit and ...

I've created https://github.com/cryptoadvance/specterext-stacktrack/issues/12

**Review by moneymanolis — APPROVED** [review]
Error is caught now and wallets overview is shown without chart if there are unconfirmed tx.

**Pull request merged**
