### PR TITLE
Make `Add Keys` more obvious

### PR DESCRIPTION
**Pull request by D4nte**
It is current not clear that "Add Keys" is the last step of the wizard.

I wonder if there is another issue where the logic to hide/display `wizard-next` and `wizard-submit` is incorrect.
Indeed, should the `Add Keys` button only be displayed once the the xpub keys are loaded?
Looking at the code, it seems that the wizard does not apply to Ledger.

Helps with #881

Before:
specter_desktop_before

After:
specter_after_change

### CODE REVIEW

**Comment by k9ert** [comment]
It's a bit difficult to judge what this PR changes effectively. Can you create a screenshot? I gues the current state is visible in 881.
Also pinging @moritzwietersheim to get some input on this.

**Comment by D4nte** [comment]
> It's a bit difficult to judge what this PR changes effectively. Can you create a screenshot? I gues the current state is visible in 881.
> Also pinging @moritzwietersheim to get some input on this.

Sorry! I took a screenshot and forgot to attach it. Now done.

**Comment by k9ert** [comment]
Nice, i like it! I'm wondering whether this is a convention we're using elsewhere as well or we don't (and should consider to document/do that).
CC @GBKS

**Comment by GBKS** [comment]
Definitely a common pattern to have primary and secondary button styles (often also a tertiary style). Primary buttons are usually much easier to pick out (often via a stronger color) and there's just one per page so it's really clear what to do next (like the green "Comment" button under this commenting form).

As far as documenting, style guides are helpful as they allow anyone to survey all UI elements, understand how they should be used and pick the right ones for their needs. For example, see the one for [Bootstrap](https://getbootstrap.com/docs/4.0/components/buttons/) or in the [Wallet UI Kit Figma file](https://www.figma.com/file/VB3GQdAnhl8yta44DY3PSV/Bitcoin-Wallet-UI-Kit?node-id=96%3A2639) I'm working on. For web-based style guides, [Storybook](https://storybook.js.org) is a pretty good solution.

**Comment by D4nte** [comment]
> Nice, i like it! I'm wondering whether this is a convention we're using elsewhere as well or we don't (and should consider to document/do that).
> CC @GBKS

Great! Yes, `btn centered action` is using in other places, that's how I came up with it. I did not want to introduce something new.

**Comment by k9ert** [comment]
Ok, LGTM, will merge soon ...

**Pull request merged**
