### PR TITLE
Bugfix: Consecutively uploading same file twice

### PR DESCRIPTION
**Pull request by relativisticelectron**
Fix for https://github.com/cryptoadvance/specter-desktop/issues/1759

### CODE REVIEW

**Comment by relativisticelectron** [comment]
@b30wulffz : Can you please check if it solves the issue also for you?

**Review by moneymanolis — APPROVED** [review]
Nice fix, thank you!

**Comment by moneymanolis** [comment]
I've just changed the comment to make clear that this is an issue for Chrome only, since Chrome is not treating it as a change event if the input value is the same whereas Firefox for example does treat it as a change event. Good idea to use the click event and a clearing of the input value!

**Comment by b30wulffz** [comment]
tested, its working very well, thanks for the fix

**Pull request merged**
