### PR TITLE
UI BugFix: Firefox:  Allow mouse selection during  address label editing

### PR DESCRIPTION
**Pull request by relativisticelectron**
Fixes: https://github.com/cryptoadvance/specter-desktop/issues/1824

It now works also in firefox:

### CODE REVIEW

**Comment by moneymanolis** [comment]
Mhh, works with and without the href attribute for me. I also don't understand the connection between removing this attribute and the mouse selection. I'll let some of the SoB participants test this as well.

**Comment by moneymanolis** [comment]
This would also break this [function](https://github.com/cryptoadvance/specter-desktop/blob/22042f4b12241db3ab0eeeaf9e5f791d08a68ca0/src/cryptoadvance/specter/templates/includes/address-label.html#L215) - even though I am not really sure why this was implemented like this. As of now at least, clicking on the address label serves as link to a explorer resource if an explorer (such as blockstream.info) is selected:

https://user-images.githubusercontent.com/70536101/183246977-e96edc9d-438a-4cc7-9a1a-b5a4cb6ee5f9.mov

**Comment by relativisticelectron** [comment]
The href link is reset every time at updating: https://github.com/cryptoadvance/specter-desktop/blob/972415a762c91528b172068707dac664419bf20f/src/cryptoadvance/specter/templates/includes/address-label.html#L219

The PR only disabled the link during editing.

**Comment by moneymanolis** [comment]
You're right, looks like the href attribute is "recovered" by setting its value in line 219. 

I am still a bit hesitant to merge this since it reduces the incentive to make the edit labelling in a proper way: either with a pop-up or at least using an input field where you input the new label. The span element is not intended for this purpose, that it is why all of this stuff pops up. There is also the issue that the caret in Firefox is just not appearing (only if you click somewhere else and then on the label).

My suggestion, let's give it a week or so and if no PR appears to tackle this until then, I'll merge this PR for the meantime. 
I am tagging @kdmukai for his information.

**Comment by relativisticelectron** [comment]
> I am still a bit hesitant to merge this since it reduces the incentive to make the edit labelling in a proper way

Interesting thought.  I agree that an `input` field (or probably test-area for long labels) would be better.

> My suggestion, let's give it a week or so and if no PR appears to tackle this until then, I'll merge this PR for the meantime.

Ok.

**Comment by moneymanolis** [comment]
I'll merge that for now as a quick improvement for Firefox users and since no PR has showed up.

**Pull request merged**
