### PR TITLE
Added install guide Issue #1884

### PR DESCRIPTION
**Pull request by j0sh21**
Please don't hesitate to reach out to me for feedback or to share a Lightning Wallet LN URL.
I acquired information about this issue through https://nodesignal.space/spenden-bitcoin-bounties/

https://github.com/cryptoadvance/specter-desktop/issues/1884

### CODE REVIEW

**Comment by k9ert** [comment]
Awesome work! I did some changes:
* added a reference in the yaml-file so that it'll get visible in the left menu
* adjusted the headings. We only want one h1 heading in each file. It determines the Menu title and the h2 level headings get submenu-items. See the [preview](https://deploy-preview-2405--specter-desktop-docs.netlify.app/install_guide/#specter-desktop-installation-methods-and-their-pros-and-cons)

Very clear and precise language. I only have two remarks:
* Why is the section  "OS-Specific Apps for Specter Desktop" coming after the comparison/decision tree ? It should imho maybe even be the first option to discuss
* the electrum connection is already here since version 2.0.0.

Can you correct those two things?

**Comment by j0sh21** [comment]
Thank you!

The decision tree is designed to help users identify the most suitable installation method based on their technical skills and preferences. When writing I thought it was logical to first guide the user through a decision-making process before introducing OS-specific apps, which are more straightforward and user-friendly options.

Based on your remarks, I made the following corrections:
- Repositioning the "OS-Specific Apps for Specter Desktop" Section.
- Updating Information about Electrum Connection.

**Comment by k9ert** [comment]
as discussed on twitter, the decision tree is a bit weirdly formatted and could profit from https://mermaid-js.github.io/

**Comment by j0sh21** [comment]
Added the mermaid graph. Please have a look.

**Comment by k9ert** [comment]
closing this PR as everything has been merged in the other PR already.

**Pull request closed without merging**
