### PR TITLE
Design Revamp Patch List #2

### LINKED ISSUE #2131: v2.0.0-pre6: Scrolling bars appear white
- Scroll bars appear white 
- Should we do blue drawers with black background? 
- Tested on MacBook M1 Pro, macos Ventura 13.0.1

https://user-images.githubusercontent.com/47259243/216158873-2765ea23-2913-4680-8461-6954bf81c129.mov

### LINKED ISSUE #2142: v2.0.0-pre6: "Rescanning Blockchain" messes up sidebar
- "Rescanning Blockchain" process messes up sidebar.
- Also the blue info icon "I" looks strange. 

image

image

### LINKED ISSUE #2144: v2.0.0-pre6: Screen Unsigned Transaction - Label off & details missing
- Send: Unsigned Transaction screen - Label is off, tries to include the receiving Bitcoin address. 
- Also not clear for the user, that he can inspect the “transaction details’. No cursor change and button too dark.

image

### LINKED ISSUE #2145: v2.0.0-pre6: Sign transaction - overlay screen off.
- Sign translation screen off. 
- Blue buttons too close to each other, when signing with QR codes with Specter DIY HWW.

image

### LINKED ISSUE #2150: "Key For Wrong Network" Alert is positioned incorrectly on device addition screen.
The tooltip is floating in the wrong location and need to be positioned correctly as seen in multiple states in below screenshot.

Screenshot 2023-02-02 at 10 54 29 AM

### LINKED ISSUE #2165: v2.0.0-pre6: Creating a multisig - device buttons are too black
- The Device buttons when setting up a multisig wallet are simply too black.
- Please adapt degree of "blackness", or add a checkmark to see what is selected.

https://user-images.githubusercontent.com/47259243/216639510-1a01c8af-d76d-4adc-a752-630d81aadee5.mov

### LINKED ISSUE #2166: v2.0.0-pre6: Export To Device - Overlay screen doesnt look right
- After creating the wallet (in this case a multisig wallet) the Export to Device overlay screen does look very good.
- ( I hope have not reported that yet, but couldn't find it, so here maybe again.)

image

### LINKED ISSUE #2172: v2.0.0-pre6: When signing "Select USB Wallet" overlay looks broken.
- When signing "Select USB Wallet" the overlay window looks broken/weird.
- Signing a Multisig here with a Jade HWW. 

(Tested on MacBook M1 Pro, macos Ventura 13.0.1)

image

https://user-images.githubusercontent.com/47259243/216699243-58054ac1-f78d-4d18-86e0-d14883a098e0.mov

### LINKED ISSUE #2175: v2.0.0-pre6: 'Broadcast Transaction' overlay screen looks off
- 'Broadcast Transaction' overlay screen looks off

(Tested on MacBook M1 Pro, macos Ventura 13.0.1)

image

https://user-images.githubusercontent.com/47259243/216730146-89da1781-9671-469b-acd5-83e2d9af7fe6.mov

### PR DESCRIPTION
**Pull request by otkstdio**
Fixes #2166
Fixes #2165
Fixes #2145
Fixes #2144
Fixes #2142
Fixes #2150
Fixes #2172
Fixes #2166
Fixes #2131
Fixes #2175

### CODE REVIEW

**Comment by moneymanolis** [comment]
The slider is still here still there and the button etc. is missing to start and stop the animation of the QR code:

grafik

**Comment by moneymanolis** [comment]
Please check master for the flow to show the "Export details". In your branch, those details are show without button click directly which makes it very hard to read.

https://user-images.githubusercontent.com/70536101/216780696-229b4ed4-e081-4f24-a3b8-1e7753e38f6b.mov

**Comment by moneymanolis** [comment]
This overlay should also only pop-up upon "Show Frankenstein QR code":

grafik

**Comment by moneymanolis** [comment]
This looks like a bit too cramped:

grafik

**Review by moneymanolis — CHANGES_REQUESTED** [review]
See comments.

**Comment by otkstdio** [comment]
@moneymanolis All issues fixed 👍

**Comment by moneymanolis** [comment]
If I am not mistaken, this issue is not fixed yet: https://github.com/cryptoadvance/specter-desktop/pull/2170#issuecomment-1416805132

**Comment by otkstdio** [comment]
@moneymanolis https://github.com/cryptoadvance/specter-desktop/pull/2170#issuecomment-1416805132 is now fixed 👍

**Review by k9ert — APPROVED** [review]

**Comment by k9ert** [comment]
Test is green, @moneymanolis is claiming that all issues are fixed. Technically an approvement is necessary but i'm merging now nevertheless.

**Pull request merged**
