### PR TITLE
fix setup tor UI

### PR DESCRIPTION
**Pull request by AtmegaBuzz**
# Tor Setup UI
## Before 
image

## After
image

image

# Node type Setup UI

## Before
image

## After
image

### CODE REVIEW

**Comment by moneymanolis** [comment]
Thank you. 
We will not support internal nodes and their setup in Specter V2, so `src/cryptoadvance/specter/templates/setup/node_type.jinja` will be deleted. 
As for `src/cryptoadvance/specter/templates/setup/tor.jinja`, we are using[ tailwind CSS](**url**) from Specter V2 onwards. Unfortunately, there is no developer documentation for it yet. In any case, could you convert the styling to use tailwind utility classes?

**Comment by otkstdio** [comment]
@AtmegaBuzz Hey! To add to what Manolis said I'd love if you could follow the left aligned design standard we have across the new UI. I've attached a screenshot to show that. 

Thanks for filling this missing piece! Appreciate it :)

Screenshot 2023-01-30 at 4 09 05 PM

**Comment by otkstdio** [comment]
@AtmegaBuzz Also i'd take a look at the classes we use for buttons, either `button` or `button bg-accent`. We'll be adding documentation in the future to make this easier for FOSS devs.

**Comment by AtmegaBuzz** [comment]
ok got it i'll fix those and how do i know which pages are being removed in new UI and which pages are incomplete and need UI fixes @otkstdio

**Comment by moneymanolis** [comment]
Would be enough I think if you applied tailwind to `src/cryptoadvance/specter/templates/setup/tor.jinja` for now.

**Comment by moneymanolis** [comment]
@AtmegaBuzz thanks for the PR, but we had to do it quickly for the release in tailwind ([here](https://github.com/cryptoadvance/specter-desktop/pull/2194)). Next time, please do styling in tailwind directly. Closing this now.

**Pull request closed without merging**
