### PR TITLE
Display address on device

### PR DESCRIPTION
**Pull request by ben-kaufman**
Added "Display Address on Device" button to the Receive tab for single signature wallets. Multisig support could be added in a similar way once HWI supports that (https://github.com/bitcoin-core/HWI/pull/324)
Solve #79

### CODE REVIEW

**Comment by stepansnigirev** [comment]
Tested, works great!

@k9ert how about including this into the release as well?

**Comment by k9ert** [comment]
Fine by me! Looks pretty isolated. I guess the current bottleneck for kicking the release out of the door is a hen/egg issue. We need a diy-binary to test desktop. I've tested multisig and the passphrase stuff but not yet the animated QR.

**Comment by stepansnigirev** [comment]
Here is my latest build.

[specter-diy.bin.zip](https://github.com/cryptoadvance/specter-desktop/files/4574177/specter-diy.bin.zip)

**Comment by k9ert** [comment]
I just tried to test this. I'm having issues, good news about this: The negtive part seems to work: "Addresses did not match! Be careful!  ...".
I'm using regtest and the expected address was something like bcr1... but the address on the trezor showed tb1qs...
Any idea why that is?

**Comment by ben-kaufman** [comment]
Yes, I had this issue too and looked in the HWI code, but seems like it’s not possible to specify to the Trezor that regtest is used (seems like it’s not supported by Trezor, not completely sure though).
However what should be possible is to convert that on our side for the verification that the addresses match, so it will still show as testnet address on the device, but our verification will not make an error because of that.

**Comment by k9ert** [comment]
Good enough! Merged.

**Pull request merged**
