### PR TITLE
Bitcoind without docker

### PR DESCRIPTION
**Pull request by k9ert**
This contains some improvements, some of them necessary for better cypress-testing:
* You can now run bitcoind without docker (`--nodocker`) if you have bitcoind on the PATH somewhere
* If you want the process to be quiet, run it with `--quiet`
* adjust the mining period, so `--mining-period 0.5` will mine a block every half a second
* `--datadir` can now be specified and the default is /tmp/bitcoind_plain_datadir. We no longer create new temp-directories
* A CTRL-C will now always terminate the process/container. In The case of docker, the datadir will be lost as well. In the case of a plain bitcoind, we now have -reset` 
* `--reset` remove the datadir
* the blockheight is now printed in the output
* All options are now properly documented

Here is an example-output:
```
(.env) ➜  specter-desktop git:(bitcoind_without_docker) ✗ python3 -m cryptoadvance.specter bitcoind --nodocker --mining-period 0.1 
Initializing HWI...
    --> starting plain bitcoind
    -->            url: http://bitcoin:secret@localhost:18443/wallet/
    --> user, password: bitcoin, secret
    -->     host, port: localhost, 18443
    -->    bitcoin-cli: bitcoin-cli -regtest -rpcuser=bitcoin -rpcpassword=secret getblockchaininfo 
    --> Now, mining a block every 0.100000 seconds, avoid it via --no-mining
    --> height: 619 | 0123456789 01^V2345^C
Aborted!
[2020-11-22 14:55:13,599] INFO in bitcoind: Killed bitcoind-process with pid 22058
(.env) ➜  specter-desktop git:(bitcoind_without_docker) ✗ python3 -m cryptoadvance.specter bitcoind --nodocker --reset             
Initializing HWI...
    --> Purging Datadirectory /tmp/bitcoind_plain_datadir ...
(.env) ➜  specter-desktop git:(bitcoind_without_docker) ✗ python3 -m cryptoadvance.specter bitcoind --nodocker --mining-period 0.1 
Initializing HWI...
    --> starting plain bitcoind
    -->            url: http://bitcoin:secret@localhost:18443/wallet/
    --> user, password: bitcoin, secret
    -->     host, port: localhost, 18443
    -->    bitcoin-cli: bitcoin-cli -regtest -rpcuser=bitcoin -rpcpassword=secret getblockchaininfo 
    --> Now, mining a block every 0.100000 seconds, avoid it via --no-mining
    --> height: 200 | 012^C
Aborted!
[2020-11-22 14:55:21,874] INFO in bitcoind: Killed bitcoind-process with pid 22113
(.env) ➜  specter-desktop git:(bitcoind_without_docker) ✗
```

### CODE REVIEW

**Comment by ben-kaufman** [comment]
Looks good! Though reset doesn't work for me, I get:
```
python3 -m cryptoadvance.specter bitcoind --reset --nodocker                  
Initializing HWI...
    --> Killing bitcoind-process with id 20807 ...
[1]    20807 terminated  python3 -m cryptoadvance.specter bitcoind --reset --nodocker
```

**Comment by k9ert** [comment]
Yeah, that wasn't quite platform-independent. Should be better now?!

**Review by ben-kaufman — APPROVED** [review]
Works now :) I see it always starts from block 200 after reset, is that intended?

**Comment by k9ert** [comment]
> Works now :) I see it always starts from block 200 after reset, is that intended?
Partially. I would have expected 100. If you restart it, all wallets in .specterd get funded with a coinbase-transaction automatically. In order to be able to spend it immediately, i'm mining 100 more blocks. Makes sense?

I can have a look whether i can reduce that to 100.

**Comment by ben-kaufman** [comment]
Ok yes makes sense, looks good to me then

**Pull request merged**
